### ISSUE TITLE
[BUG] Extensions on nested types do not work

### ISSUE THREAD

**Issue by vakhidbetrakhmadov** [Swift-CowBox/Swift-CowBox#2] opened 2024-05-03 13:47 UTC
Hi! 

There seems to be a bug, as the following snippet doesn't compile:

```swift
@CowBox struct Person {    // compilation error(s): Circular reference; Circular reference resolving attached macro 'CowBox'.
    @CowBoxNonMutating let name: String
    @CowBoxNonMutating let pet: Pet

    @CowBox struct Pet {
        @CowBoxNonMutating let name: String
    }
}

extension Person.Pet {    // compilation error(s): 'Pet' is not a member type of struct 'CowBoxClient.Person'.
    func getName() -> String {
        name
    }
}
```

On the other hand this does:

```swift
@CowBox struct Person {
    @CowBoxNonMutating let name: String
    @CowBoxNonMutating let pet: Pet

    @CowBox struct Pet {
        @CowBoxNonMutating let name: String

        func getName() -> String {
            name
        }
    }
}
```

**Comment by vakhidbetrakhmadov** [comment] 2024-05-03 16:27
Looks like an error in `swift` - https://github.com/apple/swift/issues/66450

**Comment by vanvoorden** [comment] 2024-05-03 20:01
Ahh… yes! I encountered the 66450 bug before when using `Observable` macro… but it looks like Apple did ship a fix on the 6.0 toolchain. I tried building the first snippet (with an extension on the nested type) and confirmed the error on 5.10 and confirmed the fix on 6.0. Did switching to the 6.0 toolchain fix your builds?

For now… it looks like you identified a legit 5.10 workaround: remove the extension and define the necessary functions in the main declaration of the nested type.

We could leave this task open (for now) for others to reference. We can close the task once 6.0 release goes live to production and we confirm the fix. How does that sound?

Thanks for filing a task!

**Comment by vakhidbetrakhmadov** [comment] 2024-05-06 11:01
> Did switching to the 6.0 toolchain fix your builds?

Yes, correct, it works with the following:
```bash
$ TOOLCHAINS=`plutil -extract CFBundleIdentifier raw /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2024-05-01-a.xctoolchain/Info.plist` swift -version
Apple Swift version 6.0-dev (LLVM b66077aefd3be08, Swift 84d36181a762913)
Target: arm64-apple-macosx14.0
```

But doesn't work with:
```
$ TOOLCHAINS=`plutil -extract CFBundleIdentifier raw /Library/Developer/Toolchains/swift-5.10-DEVELOPMENT-SNAPSHOT-2024-03-02-a.xctoolchain/Info.plist` swift -version 
Apple Swift version 5.10-dev (LLVM 5dc9d563e5a6cd2, Swift 9bfe759d7048cb6)
Target: arm64-apple-macosx14.0
```

**Comment by vanvoorden** [comment] 2024-09-09 19:41
Does not repro from `Xcode_16_Release_Candidate` and Swift 6. I think we are safe to close this for now as a `won't fix`. Thanks for reporting!

**Closed by vanvoorden** 2024-09-09 19:41 UTC
